/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ClientVerifiableIdentityAddress {
    /**
    * When this entry was created
    */
    'createdAt'?: string;
    /**
    * The ID
    */
    'id'?: string;
    /**
    * VerifiableAddressStatus must not exceed 16 characters as that is the limitation in the SQL Schema
    */
    'status'?: string;
    /**
    * When this entry was last updated
    */
    'updatedAt'?: string;
    /**
    * The address value  example foo@user.com
    */
    'value'?: string;
    /**
    * Indicates if the address has already been verified
    */
    'verified'?: boolean;
    'verifiedAt'?: string;
    /**
    * VerifiableAddressType must not exceed 16 characters as that is the limitation in the SQL Schema
    */
    'via'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "verified",
            "baseName": "verified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "verifiedAt",
            "baseName": "verified_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "via",
            "baseName": "via",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClientVerifiableIdentityAddress.attributeTypeMap;
    }

    public constructor() {
    }
}

