/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ClientIdentityWithCredentialsOidcConfigProvider {
    /**
    * The OpenID Connect provider to link the subject to. Usually something like `google` or `github`.
    */
    'provider'?: string;
    /**
    * The subject (`sub`) of the OpenID Connect connection. Usually the `sub` field of the ID Token.
    */
    'subject'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClientIdentityWithCredentialsOidcConfigProvider.attributeTypeMap;
    }

    public constructor() {
    }
}

