/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClientIdentityWithCredentialsOidcConfig } from '../models/ClientIdentityWithCredentialsOidcConfig';
import { HttpFile } from '../http/http';

export class ClientIdentityWithCredentialsOidc {
    'config'?: ClientIdentityWithCredentialsOidcConfig;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "config",
            "baseName": "config",
            "type": "ClientIdentityWithCredentialsOidcConfig",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClientIdentityWithCredentialsOidc.attributeTypeMap;
    }

    public constructor() {
    }
}

