/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClientIdentityState } from '../models/ClientIdentityState';
import { ClientIdentityWithCredentials } from '../models/ClientIdentityWithCredentials';
import { HttpFile } from '../http/http';

export class ClientUpdateIdentityBody {
    'credentials'?: ClientIdentityWithCredentials;
    /**
    * Store metadata about the user which is only accessible through admin APIs such as `GET /admin/identities/<id>`.
    */
    'metadataAdmin'?: any;
    /**
    * Store metadata about the identity which the identity itself can see when calling for example the session endpoint. Do not store sensitive information (e.g. credit score) about the identity in this field.
    */
    'metadataPublic'?: any;
    /**
    * SchemaID is the ID of the JSON Schema to be used for validating the identity\'s traits. If set will update the Identity\'s SchemaID.
    */
    'schemaId'?: string;
    'state'?: ClientIdentityState;
    /**
    * Traits represent an identity\'s traits. The identity is able to create, modify, and delete traits in a self-service manner. The input will always be validated against the JSON Schema defined in `schema_id`.
    */
    'traits'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "ClientIdentityWithCredentials",
            "format": ""
        },
        {
            "name": "metadataAdmin",
            "baseName": "metadata_admin",
            "type": "any",
            "format": ""
        },
        {
            "name": "metadataPublic",
            "baseName": "metadata_public",
            "type": "any",
            "format": ""
        },
        {
            "name": "schemaId",
            "baseName": "schema_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "ClientIdentityState",
            "format": ""
        },
        {
            "name": "traits",
            "baseName": "traits",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClientUpdateIdentityBody.attributeTypeMap;
    }

    public constructor() {
    }
}



