/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClientIdentityCredentialsType } from '../models/ClientIdentityCredentialsType';
import { HttpFile } from '../http/http';

export class ClientIdentityCredentials {
    'config'?: any;
    /**
    * CreatedAt is a helper struct field for gobuffalo.pop.
    */
    'createdAt'?: string;
    /**
    * Identifiers represents a list of unique identifiers this credential type matches.
    */
    'identifiers'?: Array<string>;
    'type'?: ClientIdentityCredentialsType;
    /**
    * UpdatedAt is a helper struct field for gobuffalo.pop.
    */
    'updatedAt'?: string;
    /**
    * Version refers to the version of the credential. Useful when changing the config schema.
    */
    'version'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "config",
            "baseName": "config",
            "type": "any",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifiers",
            "baseName": "identifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ClientIdentityCredentialsType",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClientIdentityCredentials.attributeTypeMap;
    }

    public constructor() {
    }
}



