/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelSampleHistogramPairHistogram } from '../models/ModelSampleHistogramPairHistogram';
import { HttpFile } from '../http/http';

export class ModelSampleHistogramPair {
    'histogram'?: ModelSampleHistogramPairHistogram;
    'timestamp'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "histogram",
            "baseName": "histogram",
            "type": "ModelSampleHistogramPairHistogram",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelSampleHistogramPair.attributeTypeMap;
    }

    public constructor() {
    }
}

