/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelHistogramBucket } from '../models/ModelHistogramBucket';
import { HttpFile } from '../http/http';

/**
* Histogram should never be nil, it\'s only stored as pointer for efficiency.
*/
export class ModelSampleHistogramPairHistogram {
    'buckets'?: Array<ModelHistogramBucket>;
    'count'?: number;
    'sum'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "buckets",
            "baseName": "buckets",
            "type": "Array<ModelHistogramBucket>",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        },
        {
            "name": "sum",
            "baseName": "sum",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelSampleHistogramPairHistogram.attributeTypeMap;
    }

    public constructor() {
    }
}

