/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ModelHistogramBucket {
    'boundaries'?: number;
    'count'?: number;
    'lower'?: number;
    'upper'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "boundaries",
            "baseName": "boundaries",
            "type": "number",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        },
        {
            "name": "lower",
            "baseName": "lower",
            "type": "number",
            "format": ""
        },
        {
            "name": "upper",
            "baseName": "upper",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelHistogramBucket.attributeTypeMap;
    }

    public constructor() {
    }
}

