/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelSampleHistogramPair } from '../models/ModelSampleHistogramPair';
import { ModelSamplePair } from '../models/ModelSamplePair';
import { HttpFile } from '../http/http';

export class ModelSampleStream {
    'histograms'?: Array<ModelSampleHistogramPair>;
    'metric'?: { [key: string]: string; };
    'values'?: Array<ModelSamplePair>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "histograms",
            "baseName": "histograms",
            "type": "Array<ModelSampleHistogramPair>",
            "format": ""
        },
        {
            "name": "metric",
            "baseName": "metric",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<ModelSamplePair>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelSampleStream.attributeTypeMap;
    }

    public constructor() {
    }
}

