/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ResourceQuantity {
    'format'?: ResourceQuantityFormatEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "format",
            "baseName": "Format",
            "type": "ResourceQuantityFormatEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResourceQuantity.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ResourceQuantityFormatEnum = "DecimalExponent" | "BinarySI" | "DecimalSI" ;

