/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1Customer } from '../models/V1Customer';
import { V1PaymentMethod } from '../models/V1PaymentMethod';
import { HttpFile } from '../http/http';

export class V1Account {
    'customer'?: V1Customer;
    'paymentMethods'?: Array<V1PaymentMethod>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customer",
            "baseName": "customer",
            "type": "V1Customer",
            "format": ""
        },
        {
            "name": "paymentMethods",
            "baseName": "paymentMethods",
            "type": "Array<V1PaymentMethod>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1Account.attributeTypeMap;
    }

    public constructor() {
    }
}

