/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1ApplicationSpecDomains } from '../models/V1alpha1ApplicationSpecDomains';
import { V1alpha1BlockStorage } from '../models/V1alpha1BlockStorage';
import { HttpFile } from '../http/http';

export class V1alpha1ApplicationSpec {
    'blockStorage'?: V1alpha1BlockStorage;
    'domains'?: V1alpha1ApplicationSpecDomains;
    /**
    * +kubebuilder:default=micro
    */
    'instance'?: string;
    'name'?: string;
    'pool'?: string;
    /**
    * +kubebuilder:default=1
    */
    'replicas'?: number;
    'type'?: string;
    'values'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "blockStorage",
            "baseName": "blockStorage",
            "type": "V1alpha1BlockStorage",
            "format": ""
        },
        {
            "name": "domains",
            "baseName": "domains",
            "type": "V1alpha1ApplicationSpecDomains",
            "format": ""
        },
        {
            "name": "instance",
            "baseName": "instance",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "pool",
            "baseName": "pool",
            "type": "string",
            "format": ""
        },
        {
            "name": "replicas",
            "baseName": "replicas",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ApplicationSpec.attributeTypeMap;
    }

    public constructor() {
    }
}

