/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ResourceQuantity } from '../models/ResourceQuantity';
import { HttpFile } from '../http/http';

export class V1alpha1BlockStorage {
    'size'?: ResourceQuantity;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "size",
            "baseName": "size",
            "type": "ResourceQuantity",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1BlockStorage.attributeTypeMap;
    }

    public constructor() {
    }
}

