/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class V1alpha1TemplateStorage {
    'blockStorage'?: boolean;
    'objectStorage'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "blockStorage",
            "baseName": "blockStorage",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "objectStorage",
            "baseName": "objectStorage",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1TemplateStorage.attributeTypeMap;
    }

    public constructor() {
    }
}

