/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1ExportBucket } from '../models/V1alpha1ExportBucket';
import { HttpFile } from '../http/http';

export class V1alpha1ExportTargetSpec {
    'bucket'?: V1alpha1ExportBucket;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bucket",
            "baseName": "bucket",
            "type": "V1alpha1ExportBucket",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ExportTargetSpec.attributeTypeMap;
    }

    public constructor() {
    }
}

