/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelSampleStream } from '../models/ModelSampleStream';
import { HttpFile } from '../http/http';

export class V1ApplicationMetrics {
    'bucket'?: Array<ModelSampleStream>;
    'cpu'?: Array<ModelSampleStream>;
    'memory'?: Array<ModelSampleStream>;
    'postgres'?: Array<ModelSampleStream>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bucket",
            "baseName": "bucket",
            "type": "Array<ModelSampleStream>",
            "format": ""
        },
        {
            "name": "cpu",
            "baseName": "cpu",
            "type": "Array<ModelSampleStream>",
            "format": ""
        },
        {
            "name": "memory",
            "baseName": "memory",
            "type": "Array<ModelSampleStream>",
            "format": ""
        },
        {
            "name": "postgres",
            "baseName": "postgres",
            "type": "Array<ModelSampleStream>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1ApplicationMetrics.attributeTypeMap;
    }

    public constructor() {
    }
}

