/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1ResourceName } from '../models/V1ResourceName';
import { V1ResourceResizeRestartPolicy } from '../models/V1ResourceResizeRestartPolicy';
import { HttpFile } from '../http/http';

export class V1ContainerResizePolicy {
    'resourceName'?: V1ResourceName;
    'restartPolicy'?: V1ResourceResizeRestartPolicy;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "resourceName",
            "baseName": "resourceName",
            "type": "V1ResourceName",
            "format": ""
        },
        {
            "name": "restartPolicy",
            "baseName": "restartPolicy",
            "type": "V1ResourceResizeRestartPolicy",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1ContainerResizePolicy.attributeTypeMap;
    }

    public constructor() {
    }
}



