/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1Address } from '../models/V1Address';
import { V1Invoice } from '../models/V1Invoice';
import { V1TaxID } from '../models/V1TaxID';
import { HttpFile } from '../http/http';

export class V1Customer {
    'address'?: V1Address;
    'balance'?: number;
    'defaultPaymentMethod'?: string;
    'email'?: string;
    'invoices'?: Array<V1Invoice>;
    'name'?: string;
    'taxID'?: V1TaxID;
    'vatRate'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "V1Address",
            "format": ""
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number",
            "format": ""
        },
        {
            "name": "defaultPaymentMethod",
            "baseName": "defaultPaymentMethod",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "invoices",
            "baseName": "invoices",
            "type": "Array<V1Invoice>",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "taxID",
            "baseName": "taxID",
            "type": "V1TaxID",
            "format": ""
        },
        {
            "name": "vatRate",
            "baseName": "vatRate",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1Customer.attributeTypeMap;
    }

    public constructor() {
    }
}

