/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1DownwardAPIVolumeFileFieldRef } from '../models/V1DownwardAPIVolumeFileFieldRef';
import { V1DownwardAPIVolumeFileResourceFieldRef } from '../models/V1DownwardAPIVolumeFileResourceFieldRef';
import { HttpFile } from '../http/http';

export class V1DownwardAPIVolumeFile {
    'fieldRef'?: V1DownwardAPIVolumeFileFieldRef;
    /**
    * Optional: mode bits used to set permissions on this file, must be an octal value between 0000 and 0777 or a decimal value between 0 and 511. YAML accepts both octal and decimal values, JSON requires decimal values for mode bits. If not specified, the volume defaultMode will be used. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set. +optional
    */
    'mode'?: number;
    /**
    * Required: Path is  the relative path name of the file to be created. Must not be absolute or contain the \'..\' path. Must be utf-8 encoded. The first item of the relative path must not start with \'..\'
    */
    'path'?: string;
    'resourceFieldRef'?: V1DownwardAPIVolumeFileResourceFieldRef;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fieldRef",
            "baseName": "fieldRef",
            "type": "V1DownwardAPIVolumeFileFieldRef",
            "format": ""
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "number",
            "format": ""
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string",
            "format": ""
        },
        {
            "name": "resourceFieldRef",
            "baseName": "resourceFieldRef",
            "type": "V1DownwardAPIVolumeFileResourceFieldRef",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1DownwardAPIVolumeFile.attributeTypeMap;
    }

    public constructor() {
    }
}

