/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1EmptyDirVolumeSourceSizeLimit } from '../models/V1EmptyDirVolumeSourceSizeLimit';
import { V1StorageMedium } from '../models/V1StorageMedium';
import { HttpFile } from '../http/http';

export class V1EmptyDirVolumeSource {
    'medium'?: V1StorageMedium;
    'sizeLimit'?: V1EmptyDirVolumeSourceSizeLimit;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "medium",
            "baseName": "medium",
            "type": "V1StorageMedium",
            "format": ""
        },
        {
            "name": "sizeLimit",
            "baseName": "sizeLimit",
            "type": "V1EmptyDirVolumeSourceSizeLimit",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1EmptyDirVolumeSource.attributeTypeMap;
    }

    public constructor() {
    }
}



