/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* sizeLimit is the total amount of local storage required for this EmptyDir volume. The size limit is also applicable for memory medium. The maximum usage on memory medium EmptyDir would be the minimum value between the SizeLimit specified here and the sum of memory limits of all containers in a pod. The default is nil which means that the limit is undefined. More info: https://kubernetes.io/docs/concepts/storage/volumes#emptydir +optional
*/
export class V1EmptyDirVolumeSourceSizeLimit {
    'format'?: V1EmptyDirVolumeSourceSizeLimitFormatEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "format",
            "baseName": "Format",
            "type": "V1EmptyDirVolumeSourceSizeLimitFormatEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1EmptyDirVolumeSourceSizeLimit.attributeTypeMap;
    }

    public constructor() {
    }
}


export type V1EmptyDirVolumeSourceSizeLimitFormatEnum = "DecimalExponent" | "BinarySI" | "DecimalSI" ;

