/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1EnvFromSourceConfigMapRef } from '../models/V1EnvFromSourceConfigMapRef';
import { V1EnvFromSourceSecretRef } from '../models/V1EnvFromSourceSecretRef';
import { HttpFile } from '../http/http';

export class V1EnvFromSource {
    'configMapRef'?: V1EnvFromSourceConfigMapRef;
    /**
    * An optional identifier to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER. +optional
    */
    'prefix'?: string;
    'secretRef'?: V1EnvFromSourceSecretRef;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "configMapRef",
            "baseName": "configMapRef",
            "type": "V1EnvFromSourceConfigMapRef",
            "format": ""
        },
        {
            "name": "prefix",
            "baseName": "prefix",
            "type": "string",
            "format": ""
        },
        {
            "name": "secretRef",
            "baseName": "secretRef",
            "type": "V1EnvFromSourceSecretRef",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1EnvFromSource.attributeTypeMap;
    }

    public constructor() {
    }
}

