/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class V1FlockerVolumeSource {
    /**
    * datasetName is Name of the dataset stored as metadata -> name on the dataset for Flocker should be considered as deprecated +optional
    */
    'datasetName'?: string;
    /**
    * datasetUUID is the UUID of the dataset. This is unique identifier of a Flocker dataset +optional
    */
    'datasetUUID'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "datasetName",
            "baseName": "datasetName",
            "type": "string",
            "format": ""
        },
        {
            "name": "datasetUUID",
            "baseName": "datasetUUID",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1FlockerVolumeSource.attributeTypeMap;
    }

    public constructor() {
    }
}

