/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1HostPathType } from '../models/V1HostPathType';
import { HttpFile } from '../http/http';

export class V1HostPathVolumeSource {
    /**
    * path of the directory on the host. If the path is a symlink, it will follow the link to the real path. More info: https://kubernetes.io/docs/concepts/storage/volumes#hostpath
    */
    'path'?: string;
    'type'?: V1HostPathType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "path",
            "baseName": "path",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "V1HostPathType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1HostPathVolumeSource.attributeTypeMap;
    }

    public constructor() {
    }
}



