/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StripeInvoiceStatus } from '../models/StripeInvoiceStatus';
import { HttpFile } from '../http/http';

export class V1Invoice {
    'amountDue'?: number;
    'amountRemaining'?: number;
    'created'?: number;
    'dueDate'?: number;
    'hostedInvoiceURL'?: string;
    'id'?: string;
    'invoicePDF'?: string;
    'number'?: string;
    'periodEnd'?: number;
    'periodStart'?: number;
    'status'?: StripeInvoiceStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amountDue",
            "baseName": "amountDue",
            "type": "number",
            "format": ""
        },
        {
            "name": "amountRemaining",
            "baseName": "amountRemaining",
            "type": "number",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number",
            "format": ""
        },
        {
            "name": "dueDate",
            "baseName": "dueDate",
            "type": "number",
            "format": ""
        },
        {
            "name": "hostedInvoiceURL",
            "baseName": "hostedInvoiceURL",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "invoicePDF",
            "baseName": "invoicePDF",
            "type": "string",
            "format": ""
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string",
            "format": ""
        },
        {
            "name": "periodEnd",
            "baseName": "periodEnd",
            "type": "number",
            "format": ""
        },
        {
            "name": "periodStart",
            "baseName": "periodStart",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "StripeInvoiceStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1Invoice.attributeTypeMap;
    }

    public constructor() {
    }
}



