/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { K8sIoApiCoreV1ConditionStatus } from '../models/K8sIoApiCoreV1ConditionStatus';
import { V1JobConditionType } from '../models/V1JobConditionType';
import { HttpFile } from '../http/http';

export class V1JobCondition {
    /**
    * Last time the condition was checked. +optional
    */
    'lastProbeTime'?: string;
    /**
    * Last time the condition transit from one status to another. +optional
    */
    'lastTransitionTime'?: string;
    /**
    * Human readable message indicating details about last transition. +optional
    */
    'message'?: string;
    /**
    * (brief) reason for the condition\'s last transition. +optional
    */
    'reason'?: string;
    'status'?: K8sIoApiCoreV1ConditionStatus;
    'type'?: V1JobConditionType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "lastProbeTime",
            "baseName": "lastProbeTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastTransitionTime",
            "baseName": "lastTransitionTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "K8sIoApiCoreV1ConditionStatus",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "V1JobConditionType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1JobCondition.attributeTypeMap;
    }

    public constructor() {
    }
}



