/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1Job } from '../models/V1Job';
import { HttpFile } from '../http/http';

export class V1JobResponse {
    'job'?: V1Job;
    'logs'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "job",
            "baseName": "job",
            "type": "V1Job",
            "format": ""
        },
        {
            "name": "logs",
            "baseName": "logs",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1JobResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

