/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1LifecyclePostStart } from '../models/V1LifecyclePostStart';
import { V1LifecyclePreStop } from '../models/V1LifecyclePreStop';
import { HttpFile } from '../http/http';

export class V1Lifecycle {
    'postStart'?: V1LifecyclePostStart;
    'preStop'?: V1LifecyclePreStop;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "postStart",
            "baseName": "postStart",
            "type": "V1LifecyclePostStart",
            "format": ""
        },
        {
            "name": "preStop",
            "baseName": "preStop",
            "type": "V1LifecyclePreStop",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1Lifecycle.attributeTypeMap;
    }

    public constructor() {
    }
}

