/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1ManagedFieldsOperationType } from '../models/V1ManagedFieldsOperationType';
import { HttpFile } from '../http/http';

export class V1ManagedFieldsEntry {
    /**
    * APIVersion defines the version of this resource that this field set applies to. The format is \"group/version\" just like the top-level APIVersion field. It is necessary to track the version of a field set because it cannot be automatically converted.
    */
    'apiVersion'?: string;
    /**
    * FieldsType is the discriminator for the different fields format and version. There is currently only one possible value: \"FieldsV1\"
    */
    'fieldsType'?: string;
    'fieldsV1'?: any;
    /**
    * Manager is an identifier of the workflow managing these fields.
    */
    'manager'?: string;
    'operation'?: V1ManagedFieldsOperationType;
    /**
    * Subresource is the name of the subresource used to update that object, or empty string if the object was updated through the main resource. The value of this field is used to distinguish between managers, even if they share the same name. For example, a status update will be distinct from a regular update using the same manager name. Note that the APIVersion field is not related to the Subresource field and it always corresponds to the version of the main resource.
    */
    'subresource'?: string;
    /**
    * Time is the timestamp of when the ManagedFields entry was added. The timestamp will also be updated if a field is added, the manager changes any of the owned fields value or removes a field. The timestamp does not update when a field is removed from the entry because another manager took it over. +optional
    */
    'time'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "apiVersion",
            "baseName": "apiVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "fieldsType",
            "baseName": "fieldsType",
            "type": "string",
            "format": ""
        },
        {
            "name": "fieldsV1",
            "baseName": "fieldsV1",
            "type": "any",
            "format": ""
        },
        {
            "name": "manager",
            "baseName": "manager",
            "type": "string",
            "format": ""
        },
        {
            "name": "operation",
            "baseName": "operation",
            "type": "V1ManagedFieldsOperationType",
            "format": ""
        },
        {
            "name": "subresource",
            "baseName": "subresource",
            "type": "string",
            "format": ""
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1ManagedFieldsEntry.attributeTypeMap;
    }

    public constructor() {
    }
}



