/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1NodeSelectorTerm } from '../models/V1NodeSelectorTerm';
import { HttpFile } from '../http/http';

/**
* If the affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to an update), the system may or may not try to eventually evict the pod from its node. +optional
*/
export class V1NodeAffinityRequiredDuringSchedulingIgnoredDuringExecution {
    /**
    * Required. A list of node selector terms. The terms are ORed.
    */
    'nodeSelectorTerms'?: Array<V1NodeSelectorTerm>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nodeSelectorTerms",
            "baseName": "nodeSelectorTerms",
            "type": "Array<V1NodeSelectorTerm>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1NodeAffinityRequiredDuringSchedulingIgnoredDuringExecution.attributeTypeMap;
    }

    public constructor() {
    }
}

