/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StripePaymentMethodType } from '../models/StripePaymentMethodType';
import { HttpFile } from '../http/http';

export class V1PaymentMethod {
    'id'?: string;
    'isDefault'?: boolean;
    'number'?: string;
    'subtype'?: string;
    'type'?: StripePaymentMethodType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isDefault",
            "baseName": "isDefault",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string",
            "format": ""
        },
        {
            "name": "subtype",
            "baseName": "subtype",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "StripePaymentMethodType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PaymentMethod.attributeTypeMap;
    }

    public constructor() {
    }
}



