/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1PodResourceClaimSource } from '../models/V1PodResourceClaimSource';
import { HttpFile } from '../http/http';

export class V1PodResourceClaim {
    /**
    * Name uniquely identifies this resource claim inside the pod. This must be a DNS_LABEL.
    */
    'name'?: string;
    'source'?: V1PodResourceClaimSource;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "V1PodResourceClaimSource",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PodResourceClaim.attributeTypeMap;
    }

    public constructor() {
    }
}

