/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { K8sIoApiCoreV1ConditionStatus } from '../models/K8sIoApiCoreV1ConditionStatus';
import { V1PodConditionType } from '../models/V1PodConditionType';
import { HttpFile } from '../http/http';

export class V1PodFailurePolicyOnPodConditionsPattern {
    'status'?: K8sIoApiCoreV1ConditionStatus;
    'type'?: V1PodConditionType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "K8sIoApiCoreV1ConditionStatus",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "V1PodConditionType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PodFailurePolicyOnPodConditionsPattern.attributeTypeMap;
    }

    public constructor() {
    }
}



