/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1PodFailurePolicyAction } from '../models/V1PodFailurePolicyAction';
import { V1PodFailurePolicyOnPodConditionsPattern } from '../models/V1PodFailurePolicyOnPodConditionsPattern';
import { V1PodFailurePolicyRuleOnExitCodes } from '../models/V1PodFailurePolicyRuleOnExitCodes';
import { HttpFile } from '../http/http';

export class V1PodFailurePolicyRule {
    'action'?: V1PodFailurePolicyAction;
    'onExitCodes'?: V1PodFailurePolicyRuleOnExitCodes;
    /**
    * Represents the requirement on the pod conditions. The requirement is represented as a list of pod condition patterns. The requirement is satisfied if at least one pattern matches an actual pod condition. At most 20 elements are allowed. +listType=atomic
    */
    'onPodConditions'?: Array<V1PodFailurePolicyOnPodConditionsPattern>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "V1PodFailurePolicyAction",
            "format": ""
        },
        {
            "name": "onExitCodes",
            "baseName": "onExitCodes",
            "type": "V1PodFailurePolicyRuleOnExitCodes",
            "format": ""
        },
        {
            "name": "onPodConditions",
            "baseName": "onPodConditions",
            "type": "Array<V1PodFailurePolicyOnPodConditionsPattern>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PodFailurePolicyRule.attributeTypeMap;
    }

    public constructor() {
    }
}



