/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1AffinityNodeAffinity } from '../models/V1AffinityNodeAffinity';
import { V1AffinityPodAffinity } from '../models/V1AffinityPodAffinity';
import { V1AffinityPodAntiAffinity } from '../models/V1AffinityPodAntiAffinity';
import { HttpFile } from '../http/http';

/**
* If specified, the pod\'s scheduling constraints +optional
*/
export class V1PodSpecAffinity {
    'nodeAffinity'?: V1AffinityNodeAffinity;
    'podAffinity'?: V1AffinityPodAffinity;
    'podAntiAffinity'?: V1AffinityPodAntiAffinity;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nodeAffinity",
            "baseName": "nodeAffinity",
            "type": "V1AffinityNodeAffinity",
            "format": ""
        },
        {
            "name": "podAffinity",
            "baseName": "podAffinity",
            "type": "V1AffinityPodAffinity",
            "format": ""
        },
        {
            "name": "podAntiAffinity",
            "baseName": "podAntiAffinity",
            "type": "V1AffinityPodAntiAffinity",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PodSpecAffinity.attributeTypeMap;
    }

    public constructor() {
    }
}

