/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1PodConditionType } from '../models/V1PodConditionType';
import { HttpFile } from '../http/http';

export class V1PodReadinessGate {
    'conditionType'?: V1PodConditionType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conditionType",
            "baseName": "conditionType",
            "type": "V1PodConditionType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PodReadinessGate.attributeTypeMap;
    }

    public constructor() {
    }
}



