/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1PodFailurePolicyOnExitCodesOperator } from '../models/V1PodFailurePolicyOnExitCodesOperator';
import { HttpFile } from '../http/http';

export class V1PodFailurePolicyOnExitCodesRequirement {
    /**
    * Restricts the check for exit codes to the container with the specified name. When null, the rule applies to all containers. When specified, it should match one the container or initContainer names in the pod template. +optional
    */
    'containerName'?: string;
    'operator'?: V1PodFailurePolicyOnExitCodesOperator;
    /**
    * Specifies the set of values. Each returned container exit code (might be multiple in case of multiple containers) is checked against this set of values with respect to the operator. The list of values must be ordered and must not contain duplicates. Value \'0\' cannot be used for the In operator. At least one element is required. At most 255 elements are allowed. +listType=set
    */
    'values'?: Array<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "containerName",
            "baseName": "containerName",
            "type": "string",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "V1PodFailurePolicyOnExitCodesOperator",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<number>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PodFailurePolicyOnExitCodesRequirement.attributeTypeMap;
    }

    public constructor() {
    }
}



