/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1SeccompProfileType } from '../models/V1SeccompProfileType';
import { HttpFile } from '../http/http';

/**
* The seccomp options to use by the containers in this pod. Note that this field cannot be set when spec.os.name is windows. +optional
*/
export class V1PodSecurityContextSeccompProfile {
    /**
    * localhostProfile indicates a profile defined in a file on the node should be used. The profile must be preconfigured on the node to work. Must be a descending path, relative to the kubelet\'s configured seccomp profile location. Must only be set if type is \"Localhost\". +optional
    */
    'localhostProfile'?: string;
    'type'?: V1SeccompProfileType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "localhostProfile",
            "baseName": "localhostProfile",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "V1SeccompProfileType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PodSecurityContextSeccompProfile.attributeTypeMap;
    }

    public constructor() {
    }
}



