/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1PreferredSchedulingTermPreference } from '../models/V1PreferredSchedulingTermPreference';
import { HttpFile } from '../http/http';

export class V1PreferredSchedulingTerm {
    'preference'?: V1PreferredSchedulingTermPreference;
    /**
    * Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
    */
    'weight'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "preference",
            "baseName": "preference",
            "type": "V1PreferredSchedulingTermPreference",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PreferredSchedulingTerm.attributeTypeMap;
    }

    public constructor() {
    }
}

