/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Specifies the output format of the exposed resources, defaults to \"1\" +optional
*/
export class V1ResourceFieldSelectorDivisor {
    'format'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "format",
            "baseName": "Format",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1ResourceFieldSelectorDivisor.attributeTypeMap;
    }

    public constructor() {
    }
}

