/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type V1ResourceName = "cpu" | "memory" | "storage" | "ephemeral-storage" | "pods" | "services" | "replicationcontrollers" | "resourcequotas" | "secrets" | "configmaps" | "persistentvolumeclaims" | "services.nodeports" | "services.loadbalancers" | "requests.cpu" | "requests.memory" | "requests.storage" | "requests.ephemeral-storage" | "limits.cpu" | "limits.memory" | "limits.ephemeral-storage" ;
