/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The capabilities to add/drop when running containers. Defaults to the default set of capabilities granted by the container runtime. Note that this field cannot be set when spec.os.name is windows. +optional
*/
export class V1SecurityContextCapabilities {
    /**
    * Added capabilities +optional
    */
    'add'?: Array<string>;
    /**
    * Removed capabilities +optional
    */
    'drop'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "add",
            "baseName": "add",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "drop",
            "baseName": "drop",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1SecurityContextCapabilities.attributeTypeMap;
    }

    public constructor() {
    }
}

