/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1AzureDataDiskCachingMode } from '../models/V1AzureDataDiskCachingMode';
import { V1AzureDataDiskKind } from '../models/V1AzureDataDiskKind';
import { HttpFile } from '../http/http';

/**
* azureDisk represents an Azure Data Disk mount on the host and bind mount to the pod. +optional
*/
export class V1VolumeAzureDisk {
    /**
    * cachingMode is the Host Caching mode: None, Read Only, Read Write. +optional
    */
    'cachingMode'?: V1AzureDataDiskCachingMode;
    /**
    * diskName is the Name of the data disk in the blob storage
    */
    'diskName'?: string;
    /**
    * diskURI is the URI of data disk in the blob storage
    */
    'diskURI'?: string;
    /**
    * fsType is Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. +optional
    */
    'fsType'?: string;
    /**
    * kind expected values are Shared: multiple blob disks per storage account  Dedicated: single blob disk per storage account  Managed: azure managed data disk (only in managed availability set). defaults to shared
    */
    'kind'?: V1AzureDataDiskKind;
    /**
    * readOnly Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. +optional
    */
    'readOnly'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cachingMode",
            "baseName": "cachingMode",
            "type": "V1AzureDataDiskCachingMode",
            "format": ""
        },
        {
            "name": "diskName",
            "baseName": "diskName",
            "type": "string",
            "format": ""
        },
        {
            "name": "diskURI",
            "baseName": "diskURI",
            "type": "string",
            "format": ""
        },
        {
            "name": "fsType",
            "baseName": "fsType",
            "type": "string",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "V1AzureDataDiskKind",
            "format": ""
        },
        {
            "name": "readOnly",
            "baseName": "readOnly",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1VolumeAzureDisk.attributeTypeMap;
    }

    public constructor() {
    }
}

