/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1CSIVolumeSourceNodePublishSecretRef } from '../models/V1CSIVolumeSourceNodePublishSecretRef';
import { HttpFile } from '../http/http';

/**
* csi (Container Storage Interface) represents ephemeral storage that is handled by certain external CSI drivers (Beta feature). +optional
*/
export class V1VolumeCsi {
    /**
    * driver is the name of the CSI driver that handles this volume. Consult with your admin for the correct name as registered in the cluster.
    */
    'driver'?: string;
    /**
    * fsType to mount. Ex. \"ext4\", \"xfs\", \"ntfs\". If not provided, the empty value is passed to the associated CSI driver which will determine the default filesystem to apply. +optional
    */
    'fsType'?: string;
    'nodePublishSecretRef'?: V1CSIVolumeSourceNodePublishSecretRef;
    /**
    * readOnly specifies a read-only configuration for the volume. Defaults to false (read/write). +optional
    */
    'readOnly'?: boolean;
    /**
    * volumeAttributes stores driver-specific properties that are passed to the CSI driver. Consult your driver\'s documentation for supported values. +optional
    */
    'volumeAttributes'?: { [key: string]: string; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "driver",
            "baseName": "driver",
            "type": "string",
            "format": ""
        },
        {
            "name": "fsType",
            "baseName": "fsType",
            "type": "string",
            "format": ""
        },
        {
            "name": "nodePublishSecretRef",
            "baseName": "nodePublishSecretRef",
            "type": "V1CSIVolumeSourceNodePublishSecretRef",
            "format": ""
        },
        {
            "name": "readOnly",
            "baseName": "readOnly",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "volumeAttributes",
            "baseName": "volumeAttributes",
            "type": "{ [key: string]: string; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1VolumeCsi.attributeTypeMap;
    }

    public constructor() {
    }
}

