/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1VolumeProjectionConfigMap } from '../models/V1VolumeProjectionConfigMap';
import { V1VolumeProjectionDownwardAPI } from '../models/V1VolumeProjectionDownwardAPI';
import { V1VolumeProjectionSecret } from '../models/V1VolumeProjectionSecret';
import { V1VolumeProjectionServiceAccountToken } from '../models/V1VolumeProjectionServiceAccountToken';
import { HttpFile } from '../http/http';

export class V1VolumeProjection {
    'configMap'?: V1VolumeProjectionConfigMap;
    'downwardAPI'?: V1VolumeProjectionDownwardAPI;
    'secret'?: V1VolumeProjectionSecret;
    'serviceAccountToken'?: V1VolumeProjectionServiceAccountToken;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "configMap",
            "baseName": "configMap",
            "type": "V1VolumeProjectionConfigMap",
            "format": ""
        },
        {
            "name": "downwardAPI",
            "baseName": "downwardAPI",
            "type": "V1VolumeProjectionDownwardAPI",
            "format": ""
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "V1VolumeProjectionSecret",
            "format": ""
        },
        {
            "name": "serviceAccountToken",
            "baseName": "serviceAccountToken",
            "type": "V1VolumeProjectionServiceAccountToken",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1VolumeProjection.attributeTypeMap;
    }

    public constructor() {
    }
}

