/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1MountPropagationMode } from '../models/V1MountPropagationMode';
import { HttpFile } from '../http/http';

export class V1VolumeMount {
    /**
    * Path within the container at which the volume should be mounted.  Must not contain \':\'.
    */
    'mountPath'?: string;
    'mountPropagation'?: V1MountPropagationMode;
    /**
    * This must match the Name of a Volume.
    */
    'name'?: string;
    /**
    * Mounted read-only if true, read-write otherwise (false or unspecified). Defaults to false. +optional
    */
    'readOnly'?: boolean;
    /**
    * Path within the volume from which the container\'s volume should be mounted. Defaults to \"\" (volume\'s root). +optional
    */
    'subPath'?: string;
    /**
    * Expanded path within the volume from which the container\'s volume should be mounted. Behaves similarly to SubPath but environment variable references $(VAR_NAME) are expanded using the container\'s environment. Defaults to \"\" (volume\'s root). SubPathExpr and SubPath are mutually exclusive. +optional
    */
    'subPathExpr'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mountPath",
            "baseName": "mountPath",
            "type": "string",
            "format": ""
        },
        {
            "name": "mountPropagation",
            "baseName": "mountPropagation",
            "type": "V1MountPropagationMode",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "readOnly",
            "baseName": "readOnly",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "subPath",
            "baseName": "subPath",
            "type": "string",
            "format": ""
        },
        {
            "name": "subPathExpr",
            "baseName": "subPathExpr",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1VolumeMount.attributeTypeMap;
    }

    public constructor() {
    }
}



