/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1VolumeProjection } from '../models/V1VolumeProjection';
import { HttpFile } from '../http/http';

/**
* projected items for all in one resources secrets, configmaps, and downward API
*/
export class V1VolumeProjected {
    /**
    * defaultMode are the mode bits used to set permissions on created files by default. Must be an octal value between 0000 and 0777 or a decimal value between 0 and 511. YAML accepts both octal and decimal values, JSON requires decimal values for mode bits. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set. +optional
    */
    'defaultMode'?: number;
    /**
    * sources is the list of volume projections +optional
    */
    'sources'?: Array<V1VolumeProjection>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "defaultMode",
            "baseName": "defaultMode",
            "type": "number",
            "format": ""
        },
        {
            "name": "sources",
            "baseName": "sources",
            "type": "Array<V1VolumeProjection>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1VolumeProjected.attributeTypeMap;
    }

    public constructor() {
    }
}

