/**
 * Cloudplane API
 * cloudplane.org API
 *
 * OpenAPI spec version: 0.1
 * Contact: support@cloudplane.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1PodAffinityTermLabelSelector } from '../models/V1PodAffinityTermLabelSelector';
import { V1PodAffinityTermNamespaceSelector } from '../models/V1PodAffinityTermNamespaceSelector';
import { HttpFile } from '../http/http';

/**
* Required. A pod affinity term, associated with the corresponding weight.
*/
export class V1WeightedPodAffinityTermPodAffinityTerm {
    'labelSelector'?: V1PodAffinityTermLabelSelector;
    'namespaceSelector'?: V1PodAffinityTermNamespaceSelector;
    /**
    * namespaces specifies a static list of namespace names that the term applies to. The term is applied to the union of the namespaces listed in this field and the ones selected by namespaceSelector. null or empty namespaces list and null namespaceSelector means \"this pod\'s namespace\". +optional
    */
    'namespaces'?: Array<string>;
    /**
    * This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching the labelSelector in the specified namespaces, where co-located is defined as running on a node whose value of the label with key topologyKey matches that of any node on which any of the selected pods is running. Empty topologyKey is not allowed.
    */
    'topologyKey'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "labelSelector",
            "baseName": "labelSelector",
            "type": "V1PodAffinityTermLabelSelector",
            "format": ""
        },
        {
            "name": "namespaceSelector",
            "baseName": "namespaceSelector",
            "type": "V1PodAffinityTermNamespaceSelector",
            "format": ""
        },
        {
            "name": "namespaces",
            "baseName": "namespaces",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "topologyKey",
            "baseName": "topologyKey",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1WeightedPodAffinityTermPodAffinityTerm.attributeTypeMap;
    }

    public constructor() {
    }
}

